import { ThemeConfig } from "../types";

export const THEMES: Record<string, ThemeConfig> = {
  grocery: {
    id: "grocery",
    name: "FreshMart",
    tagline: "Fresh Groceries Delivered to Your Door",
    icon: "🥬",
    colors: {
      primary: "#2D7A3A",
      primaryLight: "#4CAF50",
      primaryDark: "#1B5E20",
      secondary: "#FF9800",
      accent: "#FFC107",
      bg: "#F1F8E9",
      bgCard: "#FFFFFF",
      bgDark: "#1B3A1F",
      text: "#1B3A1F",
      textLight: "#558B2F",
      textMuted: "#7C9A5E",
      border: "#C5E1A5",
      danger: "#E53935",
      success: "#2E7D32",
      gradient: "linear-gradient(135deg, #2D7A3A 0%, #66BB6A 100%)",
    },
    fonts: {
      heading: "'Playfair Display', serif",
      body: "'DM Sans', sans-serif",
      size: { h1: "2.8rem", h2: "2rem", h3: "1.4rem", body: "1rem", small: "0.85rem" },
    },
    borderRadius: "16px",
    cardRadius: "20px",
    btnRadius: "12px",
  },
  ecommerce: {
    id: "ecommerce",
    name: "ShopNex",
    tagline: "Premium Shopping Experience",
    icon: "🛍️",
    colors: {
      primary: "#1A1A2E",
      primaryLight: "#16213E",
      primaryDark: "#0F0F1A",
      secondary: "#E94560",
      accent: "#FFD700",
      bg: "#F5F5F7",
      bgCard: "#FFFFFF",
      bgDark: "#1A1A2E",
      text: "#1A1A2E",
      textLight: "#4A4A5A",
      textMuted: "#8E8EA0",
      border: "#E0E0E5",
      danger: "#E94560",
      success: "#00C853",
      gradient: "linear-gradient(135deg, #1A1A2E 0%, #E94560 100%)",
    },
    fonts: {
      heading: "'Cormorant Garamond', serif",
      body: "'Outfit', sans-serif",
      size: { h1: "3.2rem", h2: "2.2rem", h3: "1.5rem", body: "1rem", small: "0.85rem" },
    },
    borderRadius: "8px",
    cardRadius: "12px",
    btnRadius: "8px",
  },
  toys: {
    id: "toys",
    name: "ToyBox",
    tagline: "Where Imagination Comes to Play!",
    icon: "🧸",
    colors: {
      primary: "#FF6B35",
      primaryLight: "#FF8A5C",
      primaryDark: "#E65100",
      secondary: "#7B2FF7",
      accent: "#FFD23F",
      bg: "#FFF8F0",
      bgCard: "#FFFFFF",
      bgDark: "#2D1B69",
      text: "#2D1B69",
      textLight: "#5C4B8A",
      textMuted: "#9B8EC4",
      border: "#F0E0FF",
      danger: "#FF4757",
      success: "#2ED573",
      gradient: "linear-gradient(135deg, #FF6B35 0%, #7B2FF7 100%)",
    },
    fonts: {
      heading: "'Fredoka', sans-serif",
      body: "'Nunito', sans-serif",
      size: { h1: "3rem", h2: "2.2rem", h3: "1.5rem", body: "1.05rem", small: "0.9rem" },
    },
    borderRadius: "24px",
    cardRadius: "28px",
    btnRadius: "50px",
  },
  pet: {
    id: "pet",
    name: "PawPalace",
    tagline: "Everything Your Pet Deserves",
    icon: "🐾",
    colors: {
      primary: "#8B5E3C",
      primaryLight: "#A67C52",
      primaryDark: "#6D4C2A",
      secondary: "#E8A87C",
      accent: "#D4E157",
      bg: "#FDF6EE",
      bgCard: "#FFFFFF",
      bgDark: "#3E2723",
      text: "#3E2723",
      textLight: "#6D4C41",
      textMuted: "#A1887F",
      border: "#EFEBE9",
      danger: "#EF5350",
      success: "#66BB6A",
      gradient: "linear-gradient(135deg, #8B5E3C 0%, #E8A87C 100%)",
    },
    fonts: {
      heading: "'Quicksand', sans-serif",
      body: "'Poppins', sans-serif",
      size: { h1: "2.8rem", h2: "2rem", h3: "1.4rem", body: "1rem", small: "0.85rem" },
    },
    borderRadius: "20px",
    cardRadius: "24px",
    btnRadius: "50px",
  },
  stationery: {
    id: "stationery",
    name: "PenCraft",
    tagline: "Premium Stationery & Office Supplies",
    icon: "✏️",
    colors: {
      primary: "#2563EB",
      primaryLight: "#3B82F6",
      primaryDark: "#1D4ED8",
      secondary: "#F97316",
      accent: "#FBBF24",
      bg: "#F0F4FF",
      bgCard: "#FFFFFF",
      bgDark: "#1E293B",
      text: "#1E293B",
      textLight: "#475569",
      textMuted: "#94A3B8",
      border: "#CBD5E1",
      danger: "#EF4444",
      success: "#22C55E",
      gradient: "linear-gradient(135deg, #2563EB 0%, #7C3AED 100%)",
    },
    fonts: {
      heading: "'Sora', sans-serif",
      body: "'Outfit', sans-serif",
      size: { h1: "2.8rem", h2: "2rem", h3: "1.4rem", body: "1rem", small: "0.85rem" },
    },
    borderRadius: "12px",
    cardRadius: "16px",
    btnRadius: "10px",
  },
  kids: {
    id: "kids",
    name: "KiddoWorld",
    tagline: "Fun, Learning & Everything Kids Love!",
    icon: "🎈",
    colors: {
      primary: "#E11D48",
      primaryLight: "#FB7185",
      primaryDark: "#BE123C",
      secondary: "#06B6D4",
      accent: "#FACC15",
      bg: "#FFF7ED",
      bgCard: "#FFFFFF",
      bgDark: "#7C2D12",
      text: "#7C2D12",
      textLight: "#9A3412",
      textMuted: "#C2410C",
      border: "#FED7AA",
      danger: "#DC2626",
      success: "#16A34A",
      gradient: "linear-gradient(135deg, #E11D48 0%, #06B6D4 100%)",
    },
    fonts: {
      heading: "'Fredoka', sans-serif",
      body: "'Nunito', sans-serif",
      size: { h1: "3rem", h2: "2.2rem", h3: "1.5rem", body: "1.05rem", small: "0.9rem" },
    },
    borderRadius: "28px",
    cardRadius: "32px",
    btnRadius: "50px",
  },
};
